/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p_pltu;

import controler.con_implementtamu;
import controler.con_interfacepetugas;
import controler.con_interfacetamu;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.mod_petugas;
import model.mod_tamu;

/**
 *
 * @author Aries Pirnando
 */
public class data_tamu extends javax.swing.JFrame {

    List<mod_tamu> record = new ArrayList<>();
    con_interfacetamu tamuserv;
    int row;
    /**
     * Creates new form data_tamu
     */
    public data_tamu() {
        initComponents();
        tamuserv = new con_implementtamu();
        this.refres();
    }
    void isitable(){
        Object data[][] = new Object[record.size()][11];
        row = 0;
        for (mod_tamu tamu: record){
            data[row][0] = tamu.getNo();
            data[row][1] = tamu.getNamaTamu();
            data[row][2] = tamu.getTanggal();
            data[row][3] = tamu.getJamMasuk();
            data[row][4] = tamu.getJamKeluar();
            data[row][5] = tamu.getYangDituju();
            data[row][6] = tamu.getNoId();
            data[row][7] = tamu.getWarnaid();
            data[row][8] = tamu.getIdTukar();
            data[row][9] = tamu.getPt();
            data[row][10] =tamu.getPesan();
            row++;
        }
        String judul[] = {"NO","NAMA","TANGGAL","MASUK","KELUAR","TUJUAN","NO ID","WARNA ID","JENIS ID","PT","PESAN"};
        jTable1.setModel(new DefaultTableModel(data,judul));
    }
    void panggil_data(){
        try {
            record = tamuserv.tampil();
        } catch (Exception e) {
            System.out.print("data tidak dapat dtampilkan");
        }
    }
    
    void refres(){
        panggil_data();
        isitable();
    }
    void tombol(){
        jtNamatamu.setEnabled(true);
        jDateChooser2.setEnabled(true);
        jtTujuan.setEnabled(true);
        jtNoid.setEnabled(true);
        jtIDditukar.setEnabled(true);
        jtPesan.setEnabled(true);
        jtPT.setEnabled(true);
        jtwarnaID.setEnabled(true);
        jtNamatamu.requestFocus();
    }
    void hapus(){
        jtCari.setText("");
        jtNamatamu.setText("");
        jtIDditukar.setText("");
        jtPT.setText("");
        jtPesan.setText("");
        jtNoid.setText("");
        jtwarnaID.setText("");
        jtTujuan.setText("");
        jtNamatamu.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        data_tamu1 = new Komponen.data_tamu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtCari = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtNamatamu = new javax.swing.JTextField();
        jtTujuan = new javax.swing.JTextField();
        jtNoid = new javax.swing.JTextField();
        jtIDditukar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPesan = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jtPT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcjam = new javax.swing.JComboBox();
        jCjamkel = new javax.swing.JComboBox();
        jcmenit = new javax.swing.JComboBox();
        jcmenkeluar = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JTNOMORNGUMPET = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jtwarnaID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        data_tamu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA TAMU");
        data_tamu1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 127, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("CETAK DATA");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        data_tamu1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 127, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        data_tamu1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 127, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Search Nama Tamu");
        data_tamu1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 187, -1, -1));

        jtCari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        data_tamu1.add(jtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 188, 353, -1));

        btCari.setText("Cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });
        data_tamu1.add(btCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 190, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        data_tamu1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 249, 643, 295));

        jButton2.setText("TAMBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        data_tamu1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 555, 90, -1));

        jButton3.setText("SIMPAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        data_tamu1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 555, 90, -1));

        jButton4.setText("EDIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        data_tamu1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 555, 90, -1));

        jButton5.setText("HAPUS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        data_tamu1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 555, 90, -1));

        jButton6.setText("KELUAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        data_tamu1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 555, 90, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("NAMA TAMU");
        data_tamu1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("TANGGAL");
        data_tamu1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("JAM");
        data_tamu1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("MASUK");
        data_tamu1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("KELUAR");
        data_tamu1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("TUJUAN");
        data_tamu1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("NO ID");
        data_tamu1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("ID DITUKAR");
        data_tamu1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("PESAN");
        data_tamu1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jtNamatamu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtNamatamu.setEnabled(false);
        data_tamu1.add(jtNamatamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 214, 234, -1));

        jtTujuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtTujuan.setEnabled(false);
        data_tamu1.add(jtTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 234, -1));

        jtNoid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtNoid.setEnabled(false);
        data_tamu1.add(jtNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 234, -1));

        jtIDditukar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtIDditukar.setEnabled(false);
        data_tamu1.add(jtIDditukar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 234, -1));

        jtPesan.setColumns(20);
        jtPesan.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtPesan.setRows(5);
        jtPesan.setEnabled(false);
        jScrollPane2.setViewportView(jtPesan);

        data_tamu1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 234, 77));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("DATA TAMU");
        data_tamu1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 178, -1, -1));

        jtPT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtPT.setEnabled(false);
        data_tamu1.add(jtPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 234, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("PT");
        data_tamu1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jcjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08", "09", "10", "11", "12", "13", "14", "15", "16", "17" }));
        data_tamu1.add(jcjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jCjamkel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08", "09", "10", "11", "12", "13", "14", "15", "16", "17" }));
        data_tamu1.add(jCjamkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jcmenit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        data_tamu1.add(jcmenit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jcmenkeluar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        data_tamu1.add(jcmenkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText(":");
        data_tamu1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 268, 6, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText(":");
        data_tamu1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 294, 6, -1));

        JTNOMORNGUMPET.setText("jTextField1");
        data_tamu1.add(JTNOMORNGUMPET, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 112, 0, -1));

        jDateChooser2.setEnabled(false);
        data_tamu1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 241, -1, -1));

        jtwarnaID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtwarnaID.setEnabled(false);
        data_tamu1.add(jtwarnaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 234, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("WARNA ID");
        data_tamu1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_tamu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(data_tamu1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Cetak_datatamu().show();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        // TODO add your handling code here:
        try {
            record = tamuserv.cari(jtCari.getText());
        } catch (Exception e) {
            System.out.print("data tidak dapat dtampilkan");
        }
        isitable();
    }//GEN-LAST:event_btCariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tombol();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String tanggal ="YYYY-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(tanggal);
        String tampil = String.valueOf(format.format(jDateChooser2.getDate()));
        
         try {
            mod_tamu input = new mod_tamu();
            input.setNamaTamu(jtNamatamu.getText());
            input.setTanggal(tampil);
            input.setJamMasuk(jcjam.getSelectedItem().toString()+" : "+jcmenit.getSelectedItem().toString());
            input.setJamKeluar(jCjamkel.getSelectedItem().toString()+" : "+jcmenkeluar.getSelectedItem().toString());
            input.setYangDituju(jtTujuan.getText());
            input.setNoId(jtNoid.getText());
            input.setWarnaid(jtwarnaID.getText());
            input.setIdTukar(jtIDditukar.getText());
            input.setPt(jtPT.getText());
            input.setPesan(jtPesan.getText());
            tamuserv.simpan(input);
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            this.refres();
            hapus();
        } catch (Exception e) {
             
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String tanggal ="yyyy-mm-dd";
        SimpleDateFormat format = new SimpleDateFormat(tanggal);
        String tampil = String.valueOf(format.format(jDateChooser2.getDate()));
        try {
            mod_tamu input = new mod_tamu();
            input.setNamaTamu(jtNamatamu.getText());
            input.setTanggal(tampil);
            input.setJamMasuk(jcjam.getSelectedItem().toString()+" : "+jcmenit.getSelectedItem().toString());
            input.setJamKeluar(jCjamkel.getSelectedItem().toString()+" : "+jcmenit.getSelectedItem().toString());
            input.setYangDituju(jtTujuan.getText());
            input.setNoId(jtNoid.getText());
            input.setWarnaid(jtwarnaID.getText());
            input.setIdTukar(jtIDditukar.getText());
            input.setPt(jtPT.getText());
            input.setPesan(jtPesan.getText());
            input.setNo(Integer.valueOf(JTNOMORNGUMPET.getText()));
            tamuserv.ubah(input);
            JOptionPane.showMessageDialog(null,"Data berhasil diedit");
            this.refres();
            hapus();
        } catch (Exception e) {
            }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         if(jTable1.getSelectedColumnCount()==1){
            int x = jTable1.getSelectedRow();
            JTNOMORNGUMPET.setText(jTable1.getValueAt(x, 0).toString());
            jtNamatamu.setText(jTable1.getValueAt(x, 1).toString());
            jtTujuan.setText(jTable1.getValueAt(x, 5).toString());
            jtNoid.setText(jTable1.getValueAt(x, 6).toString());
            jtwarnaID.setText(jTable1.getValueAt(x, 7).toString());
            jtIDditukar.setText(jTable1.getValueAt(x, 8).toString());
            jtPT.setText(jTable1.getValueAt(x,9).toString());
            jtPesan.setText(jTable1.getValueAt(x,10).toString());
            tombol();
         }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            mod_tamu input = new mod_tamu();
            tamuserv.hapus(JTNOMORNGUMPET.getText());
            JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
            this.refres();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_tamu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTNOMORNGUMPET;
    private javax.swing.JButton btCari;
    private Komponen.data_tamu data_tamu1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCjamkel;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcjam;
    private javax.swing.JComboBox jcmenit;
    private javax.swing.JComboBox jcmenkeluar;
    private javax.swing.JTextField jtCari;
    private javax.swing.JTextField jtIDditukar;
    private javax.swing.JTextField jtNamatamu;
    private javax.swing.JTextField jtNoid;
    private javax.swing.JTextField jtPT;
    private javax.swing.JTextArea jtPesan;
    private javax.swing.JTextField jtTujuan;
    private javax.swing.JTextField jtwarnaID;
    // End of variables declaration//GEN-END:variables
}
